/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e00db25a4f4b55911b4454f
*
* You will get 10% discount for each one of your friends
* 
*/
// Import Libraries
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
// Import Services
import { UserService } from '../../services/user.service';
import { BakeryBasketService } from '../../services/bakery-basket.service';
// Import Models
import { BakeryBasket } from '../../domain/bakery-basket_db/bakery-basket';
import { User } from '../../domain/bakery-basket_db/user';

// START - USED SERVICES
/**
* UserService.create
*	@description CRUD ACTION create
*
* BakeryBasketService.delete
*	@description CRUD ACTION delete
*	@param ObjectId id Id
*
* BakeryBasketService.findByShubham
*	@description CRUD ACTION findByShubham
*	@param Objectid key Id della risorsa Shubham da cercare
*
* UserService.get
*	@description CRUD ACTION get
*	@param ObjectId id Id resource
*
* BakeryBasketService.list
*	@description CRUD ACTION list
*
* UserService.update
*	@description CRUD ACTION update
*	@param ObjectId id Id
*
*/
// END - USED SERVICES

/**
 * This component allows to edit a BakeryBasket
 */
@Component({
    selector: 'app-user-edit',
    templateUrl: 'user-edit.component.html',
    styleUrls: ['user-edit.component.css']
})
export class UserEditComponent implements OnInit {
    item: BakeryBasket;
    listUserShubham: User[];
    model: BakeryBasket;
    formValid: Boolean;

    constructor(
    private userService: UserService,
    private bakerybasketService: BakeryBasketService,
    private route: ActivatedRoute,
    private location: Location) {
        // Init item
        this.item = new BakeryBasket();
    }

    /**
     * Init
     */
    ngOnInit() {
        this.route.params.subscribe(param => {
            const id: string = param['id'];
            if (id !== 'new') {
                this.bakerybasketService.get(id).subscribe(item => this.item = item);
            }
            // Get relations
            this.userService.list().subscribe(list => this.listUserShubham = list);
        });
    }

    /**
     * Check if an User is in  Shubham
     *
     * @param {string} id Id of User to search
     * @returns {boolean} True if it is found
     */
    containUser(id: string): boolean {
        if (!this.item.Shubham) return false;
        return this.item.Shubham.indexOf(id) !== -1;
    }

    /**
     * Add User from BakeryBasket
     *
     * @param {string} id Id of User to add in this.item.Shubham array
     */
    addUser(id: string) {
        if (!this.item.Shubham)
            this.item.Shubham = [];
        this.item.Shubham.push(id);
    }

    /**
     * Remove an User from a BakeryBasket
     *
     * @param {number} index Index of User in this.item.Shubham array
     */
    removeUser(index: number) {
        this.item.Shubham.splice(index, 1);
    }

    /**
     * Save BakeryBasket
     *
     * @param {boolean} formValid Form validity check
     * @param BakeryBasket item BakeryBasket to save
     */
    save(formValid: boolean, item: BakeryBasket): void {
        this.formValid = formValid;
        if (formValid) {
            if (item._id) {
                this.bakerybasketService.update(item).subscribe(data => this.goBack());
            } else {
                this.bakerybasketService.create(item).subscribe(data => this.goBack());
            } 
        }
    }

    /**
     * Go Back
     */
    goBack(): void {
        this.location.back();
    }


}



